name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches: [ main ]
  # Allow you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create artifact directory
        run: |
          mkdir -p ${{ runner.temp }}/artifact
          cp -r dist/* ${{ runner.temp }}/artifact/

      - name: Upload artifact
        shell: bash
        run: |
          cd ${{ runner.temp }}/artifact
          if [ -f "../artifact.tar" ]; then rm ../artifact.tar; fi
          tar czf ../artifact.tar .
          echo "::group::Upload artifact"
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/x-tar" \
            --data-binary "@../artifact.tar" \
            "https://api.github.com/repos/${{ github.repository }}/pages/artifacts"
          echo "::endgroup::"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 